// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajatpjfzifznklkfiyfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqYXRwamZ6aWZ6bmtsa2ZpeWZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NjQ2NjMsImV4cCI6MjA2OTU0MDY2M30.wA_sS9xy_ZTHF03czypOKLyxt152EVUf2jvY1HFNizk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});